//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToVfp.Northwind.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqToVfp.Northwind.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CharByteArrayDataZip {
            get {
                object obj = ResourceManager.GetObject("CharByteArrayDataZip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DecimalTableZip {
            get {
                object obj = ResourceManager.GetObject("DecimalTableZip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;baselines&gt;
        ///  &lt;baseline key=&quot;TestWhereWithCurrency&quot;&gt;
        ///    SELECT t0.CustomerID, t0.Freight, t0.OrderDate, t0.OrderID, t0.ShipCountry
        ///    FROM Orders AS t0
        ///    WHERE ((t0.CustomerID = @__Param__0__) AND (t0.Freight = @__Param__1__))
        ///  &lt;/baseline&gt;
        ///  &lt;baseline key=&quot;TestWhereTrimStartChars&quot;&gt;
        ///    SELECT t0.City, t0.CompanyName, t0.ContactName, t0.Country, t0.CustomerID, t0.Phone 
        ///    FROM Customers AS t0 
        ///    WHERE (LTRIM(t0.City,&apos;L&apos;,&apos;o&apos;) = @__Param__0__)
        ///  &lt;/base [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthwindTranslationXml {
            get {
                return ResourceManager.GetString("NorthwindTranslationXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NorthwindVfpZip {
            get {
                object obj = ResourceManager.GetObject("NorthwindVfpZip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///	&lt;Entity Id=&quot;Customers&quot;&gt;
        ///		&lt;Table Name=&quot;Customers&quot; /&gt;
        ///		&lt;Column Member = &quot;CustomerId&quot; IsPrimaryKey = &quot;true&quot; /&gt;
        ///		&lt;Column Member = &quot;ContactName&quot; /&gt;
        ///		&lt;Column Member = &quot;CompanyName&quot; /&gt;
        ///		&lt;Column Member = &quot;Phone&quot; /&gt;
        ///		&lt;Column Member = &quot;City&quot; DbType=&quot;NVARCHAR(20)&quot; /&gt;
        ///		&lt;Column Member = &quot;Country&quot; /&gt;
        ///		&lt;Association Member = &quot;Orders&quot; KeyMembers = &quot;CustomerID&quot; RelatedEntityID = &quot;Orders&quot; RelatedKeyMembers = &quot;CustomerID&quot; /&gt;
        ///	&lt;/Entity&gt;
        ///	&lt;Entity Id=&quot;Orders&quot;&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthwindXml {
            get {
                return ResourceManager.GetString("NorthwindXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map&gt;
        ///	&lt;Entity Id=&quot;Customer&quot;&gt;
        ///		&lt;Table Name=&quot;Customers&quot;/&gt;
        ///		&lt;Column Member=&quot;City&quot; /&gt;
        ///		&lt;Column Member=&quot;CompanyName&quot; /&gt;
        ///		&lt;Column Member=&quot;ContactName&quot; /&gt;
        ///		&lt;Column Member=&quot;Country&quot; /&gt;
        ///		&lt;Column Member=&quot;CustomerID&quot; IsPrimaryKey=&quot;true&quot; /&gt;
        ///		&lt;Column Member=&quot;Phone&quot; /&gt;
        ///        &lt;Association Member=&quot;Orders&quot; KeyMembers=&quot;CustomerID&quot; RelatedEntityID=&quot;Order&quot; RelatedKeyMembers=&quot;CustomerID&quot; /&gt;					
        ///	&lt;/Entity&gt;
        ///	&lt;Entity Id=&quot;EmpT&quot;&gt;
        ///		&lt;Table Name=&quot;EmployeeTerritories&quot;/&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RepositoryMappingXml {
            get {
                return ResourceManager.GetString("RepositoryMappingXml", resourceCulture);
            }
        }
    }
}
